#!/bin/bash

##--------------------------------------------------------------------
## Copyright (c) 2018 Dianomic Systems
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##--------------------------------------------------------------------
##
## Author: Massimiliano Pinto
##

set -e

architecture="none"
plugin_type="south"
plugin_name="opcua"
plugin_install_dirname="opcua"
usage="$(basename "$0") {x86|arm} [help|clean|cleanall]
This script is used to create the Debian package of FoglAMP C++ '${plugin_name}' ${plugin_type} plugin
Arguments:
 help     - Display this help text
 x86      - Build an x86_64 package
 arm      - Build an armv7l package
 clean    - Remove all the old versions saved in format .XXXX
 cleanall - Remove all the versions, including the last one"

GIT_ROOT=`pwd`    # The script must be executed from the root git directory
if [ $# -gt 0 ]; then
    for i in "$@"
    do
        case "$i" in
          x86)
              architecture="x86_64"
              shift
              ;;
          arm)
              architecture="armhf"
              shift
              ;;
          clean)
              echo -n "Cleaning the build folder from older versions..."
              find "${GIT_ROOT}/packages/build" -maxdepth 1 | grep '.*\.[0-9][0-9][0-9][0-9]' | xargs rm -rf
              echo "Done."
              shift
              ;;
          cleanall)
              if [ -d "${GIT_ROOT}/packages/build" ]; then
                  echo -n "Cleaning the build folder..."
                  rm -rf ${GIT_ROOT}/packages/build/*
                  echo "Done."
              else
                  echo "No build folder, skipping cleanall"
              fi
              shift
              ;;
          help)
              echo "${usage}"
              exit 0
              ;;
          *)
              echo "Unrecognized option: $i"
             exit 1
            ;;
      esac
    done
else
  echo "See help and select the architecture to use, *x86* or *arm*"
  exit 1
fi

# If the architecture has not been defined, then the script is complete
if [[ "$architecture" == "none" ]]; then
  exit 0
fi

# Get plugin version from plugin.cpp, grep comment: // Version
plugin_version=`cat ${GIT_ROOT}/plugin.cpp | grep 'Version' | head -1 | tr -d ' ' | awk -F',' '{print $1}' | sed -e 's/\"//g' | sed -e 's/[[:space:]]\+//g'`
# Get FogLAMP version dependency from foglamp_version file
foglamp_version=`cat ${GIT_ROOT}/foglamp.version | tr -d ' ' | grep 'foglamp_version' | head -1 | sed -e 's/\(.*\)version\(.*\)/\2/g'`
BUILD_ROOT="${GIT_ROOT}/packages/build"

# Final package name
package_name="foglamp-${plugin_type}-${plugin_name}-${plugin_version}-${architecture}"

# Print the summary of findings
echo "The package root directory is   : ${GIT_ROOT}"
echo "The FogLAMP required version    : ${foglamp_version}"
echo "The package will be built in    : ${BUILD_ROOT}"
echo "The architecture is set as      : ${architecture}"
echo "The package name is             : ${package_name}"
echo

# Create the package directory. If a directory with the same name exists,
# it is copied with a version number.

# First, create the BUILD_ROOT folder, if necessary
if [ ! -L "${BUILD_ROOT}" -a ! -d "${BUILD_ROOT}" ]; then
    mkdir -p "${BUILD_ROOT}"
fi

# Checl plugin has been built
if [ ! -d "${GIT_ROOT}/build" ]; then
    echo "Error: ./build directory not found."
    echo "Build plugin ${plugin_name} first."
    echo "mkdir ./build; cd ./build; cmake ..; make; cd .."
    exit 1
fi

cd "${BUILD_ROOT}"
existing_pkgs=`find . -maxdepth 1 -name "${package_name}.????" | wc -l`
existing_pkgs=$((existing_pkgs+1))
new_stored_pkg=$(printf "${package_name}.%04d" "${existing_pkgs}")
if [ -d "${package_name}" ]; then
    echo "Saving the old working environment as ${new_stored_pkg}"
    mv "${package_name}" "${new_stored_pkg}"
fi
mkdir "${package_name}"

# Populate the package directory with Debian files
# First with files common to all pla
echo -n "Populating the package and updating version file..."
cd "${package_name}"
cp -R ${GIT_ROOT}/packages/Debian/common/* .
cp -R ${GIT_ROOT}/packages/Debian/${architecture}/* .
sed -i "s/Version: 1.0.0/Version: ${plugin_version}/g" DEBIAN/control
sed -i "s/Depends: foglamp/Depends: foglamp (${foglamp_version})/g" DEBIAN/control

mkdir -p usr/local/foglamp
cd usr/local/foglamp
mkdir -p "plugins/${plugin_type}/${plugin_install_dirname}"
cp -R --preserve=links ${GIT_ROOT}/build/lib*.so* "plugins/${plugin_type}/${plugin_install_dirname}"
echo "Done."

# Build the package
cd "${BUILD_ROOT}"

# Save the old versions
existing_pkgs=`find . -maxdepth 1 -name "${package_name}.deb.????" | wc -l`
existing_pkgs=$((existing_pkgs+1))
new_stored_pkg=$(printf "${package_name}.deb.%04d" "${existing_pkgs}")

if [ -e "${package_name}.deb" ]; then
    echo "Saving the old package as ${new_stored_pkg}"
    mv "${package_name}.deb" "${new_stored_pkg}"
fi

echo "Building the new package..."
dpkg-deb --build ${package_name}
echo "Building Complete."

exit 0
